Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.hostname = "puppet-master"
	config.vm.network "private_network", ip: "192.168.56.100"
	config.vm.provider "virtualbox" do |vb|
		vb.name = "puppt-server"
		vb.memory = "2048"
	end
	config.vm.provision "file", source: "./puppet-conf/puppet", destination: "~/puppet"
	config.vm.provision "file", source: "./puppet-conf/puppet.conf", destination: "~/puppet.conf"
	config.vm.provision "file", source: "./puppet-conf/puppetserver", destination: "~/puppetserver"
	config.vm.provision "shell", inline: <<-SHELL
		sudo echo "192.168.56.100  master.puppet.com" | sudo tee -a /etc/hosts
		sudo echo "192.168.56.101  agent01.puppet.com" | sudo tee -a /etc/hosts
		sudo apt-get update
		sudo apt-get upgrade -y
		sudo apt-get install sysv-rc-conf chrony -y
		export LC_ALL=en_US.UTF-8
		sudo service chrony start
		sudo ysv-rc-conf chrony on
		sudo timedatectl set-timezone Asia/Taipei
		wget https://apt.puppetlabs.com/puppet-release-xenial.deb
		sudo dpkg -i puppet-release-xenial.deb
		sudo apt-get update
		sudo apt-get install puppetserver -y
		sudo mv /home/vagrant/puppet /etc/default/puppet
		sudo mv /home/vagrant/puppet.conf /etc/puppetlabs/puppet/puppet.conf
		sudo mv /home/vagrant/puppetserver /etc/default/puppetserver
		sudo ln -s /opt/puppetlabs/puppet/bin/puppet /usr/sbin/
		sudo systemctl start puppetserver
		sudo systemctl enable puppetserver
		sudo ufw disable
	SHELL
end
